version: '3'
services:
  mysql:
    restart: always
    container_name: mysql
    image: library/mariadb:10.3
    env_file: mariadb.env

    volumes:
      - mysql_config:/etc/mysql
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
    ports:
      - 0.0.0.0:3306:3306

volumes:
  mysql_config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mysql/config
      o: bind
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mysql/data
      o: bind

